title: A R M A
description: Personal BLOG.

url:
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: armandoahir
    twitter:
    facebook:
    email: armandoahir@proton.me
    linkedin:
    youtube:
    tumblr:

google_analytics: "UA-58263416-1"

disqus:
    shortname: arma
