title: Arma Labs
email: armandoahir31@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.armalabs.cc.cd" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.jpg
github_username:  armandoahir
# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
